### PR TITLE
Add plugins to resolve hacks that were needed for the MkDocs build

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by shafr** [comment]
Is `gen_index.py` really necessary ? I'm doing chapters replacement in the flow:
```
      - name: Copy Readme
        run: |
            cp README.md chapters/      
      - name: Remove chapters prefix from README links.
        run: |
            sed -ire "s;./chapters/;;g" chapters/README.md
```
And the generated index seems to be just fine. Can I skip that python file than ?

**Comment by shafr** [comment]
Strange, changing identation for README.MD file now fails `lint:consistency` job and I'm not able to resolve it:
https://github.com/shafr/CEH-in-bullet-points/runs/3583182128?check_suite_focus=true

**Comment by oprypin** [comment]
@shafr In your setup you can't just run `mkdocs build`. Any new contributor would have to find the separate commands and run them every time. With the Python file everything is self-contained and doesn't leave behind stray files.

> changing identation for README.MD file now fails lint:consistency job

That is true. MkDocs requires 4 spaces (doesn't work well otherwise) and this lint check requires 3 spaces (just because).
That check surely has some config but I haven't looked.

**Comment by shafr** [comment]
Can you please revert README.md (so checks would not fail) &
update your gen_index.py so it would replace 4 spaces tp 3 spaces ? 
Something in terms of (not sure how it is properly chained in python or if it;s better to use extra variable there):
```
out_f.write(re.sub(r'^\.\.\.\.', '\.\.\.', line)
out_f.write(re.sub(r'^\.\.\.\.\.\.\.\.', '\.\.\.\.\.\.', line)
```

**Pull request merged**
